part of IrcModule;

class STRINGS {
  static RegExp servername;
  static RegExp nickname;
  static RegExp host;
  static RegExp message;
  static RegExp prefix;
  static RegExp mode;
  static RegExp nospcrlfcl;
  static RegExp middle;
  static RegExp trailing;
  static String space = " ";
  static String crlf = new Utf8Decoder().convert([13,10]);
}


class CLIENT_COMMANDS {
  static String PASS = "PASS";
  static String NICK = "NICK";
  static String USER = "USER";
  static String OPER = "OPER";
  static String USER_MODE = "MODE";
  static String SERVICE = "SERVICE";
  static String QUIT = "QUIT";
  static String SQUIT = "SQUIT";
  static String JOIN = "JOIN";
  static String PART = "PART";
  static String CHAN_MODE = "MODE";
  static String TOPIC = "TOPIC";
  static String NAMES = "NAMES";
  static String LIST = "LIST";
  static String INVITE = "INVITE";
  static String KICK = "KICK";
  static String PRIV_MSG = "SQUIT";
  static String NOTICE = "NOTICE";
  static String MOTD = "MOTD";
  static String L_USERS = "LUSERS";
  static String VERSION = "VERSION";
  static String STATS = "STATS";
  static String LINKS = "LINKS";
  static String TIME = "TIME";
  static String CONNECT = "CONNECT";
  static String TRACE = "TRACE";
  static String ADMIN = "ADMIN";
  static String INFO = "INFO";
  static String SERV_LIST = "SERVLIST";
  static String SQUERY = "SQUERY";
  static String WHO = "WHO";
  static String WHO_IS = "WHOIS";
  static String WHO_WAS = "WHOWAS";
  static String KILL = "KILL";
  static String PING = "PING";
  static String PONG = "PONG";
  static String ERROR = "ERROR";
  static String AWAY = "AWAY";
  static String REHASH = "REHASH";
  static String DIE = "DIE";
  static String RESTART = "RESTART";
  static String SUMMON= "SUMMON";
  static String USERS = "USERS";
  static String WALL_OPS = "WALLOPS";
  static String USER_HOST = "USERHOST";
  static String IS_ON = "ISON";
  
}

class NUMERIC_REPLIES {
  // Errors

  static int ERR_NOSUCHNICK = 401;
  static int ERR_NOSUCHSERVER = 402;
  static int ERR_NOSUCHCHANNEL = 403;
  static int ERR_CANNOTSENDTOCHAN = 404;
  static int ERR_TOOMANYCHANNELS = 405;
  static int ERR_WASNOSUCHNICK = 406;
  static int ERR_TOOMANYTARGETS = 407;
  static int ERR_NOSUCHSERVICE = 408;
  static int ERR_NOORIGIN = 409;
  static int ERR_NORECIPIENT = 411;
  static int ERR_NOTEXTTOSEND = 412;
  static int ERR_NOTOPLEVEL = 413;
  static int ERR_WILDTOPLEVEL = 414;
  static int ERR_BADMASK = 415;
  static int ERR_UNKNOWNCOMMAND = 421;
  static int ERR_NOMOTD = 422;
  static int ERR_NOADMININFO = 423;
  static int ERR_FILEERROR = 424;
  static int ERR_NONICKNAMEGIVEN = 431;
  static int ERR_ERRONEUSNICKNAME = 432;
  static int ERR_NICKNAMEINUSE = 433;
  static int ERR_NICKCOLLISION = 436;
  static int ERR_UNAVAILRESOURCE = 437;
  static int ERR_USERNOTINCHANNEL = 441;
  static int ERR_NOTONCHANNEL = 442;
  static int ERR_USERONCHANNEL = 443;
  static int ERR_NOLOGIN = 444;
  static int ERR_SUMMONDISABLED = 445;
  static int ERR_USERSDISABLED = 446;
  static int ERR_NOTREGISTERED = 451;
  static int ERR_NEEDMOREPARAMS = 461;
  static int ERR_ALREADYREGISTRED = 462;
  static int ERR_NOPERMFORHOST = 463;
  static int ERR_PASSWDMISMATCH = 464;
  static int ERR_YOUREBANNEDCREEP = 465;
  static int ERR_YOUWILLBEBANNED = 466;
  static int ERR_KEYSET = 467;
  static int ERR_CHANNELISFULL = 471;
  static int ERR_UNKNOWNMODE = 472;
  static int ERR_INVITEONLYCHAN = 473;
  static int ERR_BANNEDFROMCHAN = 474;
  static int ERR_BADCHANNELKEY = 475;
  static int ERR_BADCHANMASK = 476;
  static int ERR_NOCHANMODES = 477;
  static int ERR_BANLISTFULL = 478;
  static int ERR_NOPRIVILEGES = 481;
  static int ERR_CHANOPRIVSNEEDED = 482;
  static int ERR_CANTKILLSERVER = 483;
  static int ERR_RESTRICTED = 484;
  static int ERR_UNIQOPPRIVSNEEDED = 485;
  static int ERR_NOOPERHOST = 491;
  static int ERR_UMODEUNKNOWNFLAG = 501;
  static int ERR_USERSDONTMATCH = 502;
  
  // Replies
  static int RPL_WELCOME = 001;
  static int RPL_YOUREHOST = 002;
  static int RPL_CREATED = 003;
  static int RPL_MYINFO = 004;
  static int RPL_BOUNCE = 005;
  static int RPL_USERHOST = 302;
  static int RPL_ISON = 303;
  static int RPL_AWAY = 301;
  static int RPL_UNAWAY = 305;
  static int RPL_NOWAWAY = 306;
  static int RPL_WHOISUSER = 311;
  static int RPL_WHOISSERVER = 312;
  static int RPL_WHOISOPERATOR = 313;
  static int RPL_WHOISIDLE = 317;
  static int RPL_ENDOFWHOIS = 318;
  static int RPL_WHOISCHANNELS = 319;
  static int RPL_WHOWASUSER = 314;
  static int RPL_ENDOFWHOWAS = 369;
  
  // @depreciated 
  static int RPL_LISTSTART = 321;
  
  static int RPL_LIST = 322;
  static int RPL_LISTEND = 323;
  static int RPL_UNIQOPIS = 325;
  static int RPL_CHANNELMODEIS = 324;
  static int RPL_INVITING = 341;
  static int RPL_SUMMONING = 342;
  static int RPL_INVITELIST = 346;
  static int RPL_ENDOFINVITELIST = 347;
  static int RPL_EXCEPTLIST = 348;
  static int RPL_ENDOFEXCEPTLIST = 349;
  static int RPL_VERSION = 351;
  static int RPL_WHOREPLY = 352;
  static int RPL_ENDOFWHO = 315;
  static int RPL_NAMREPLY = 353;
  static int RPL_ENDOFNAMES = 366;
  static int RPL_LINKS = 364;
  static int RPL_ENDOFLINKS = 365;
  static int RPL_BANLIST = 367;
  static int RPL_ENDOFBANLIST = 368;
  static int RPL_INFO = 371;
  static int RPL_ENDOFINFO = 374;
  static int RPL_MOTDSTART = 375;
  static int RPL_MOTD = 372;
  static int RPL_ENDOFMOTD = 376;
  static int RPL_YOUREOPER = 381;
  static int RPL_REHASHING = 382;
  static int RPL_YOURESERVICE = 383;
  static int RPL_TIME = 391;
  static int RPL_USERSSTART = 392;
  static int RPL_USERS = 393;
  static int RPL_ENDOFUSERS = 394;
  static int RPL_NOUSERS = 395;
  static int RPL_TRACELINK = 200;
  static int RPL_TRACECONNECTING = 201;
  static int RPL_TRACEHANDSHAKE = 202;
  static int RPL_TRACEUNKNOWN = 203;
  static int RPL_TRACEOPERATOR = 204;
  static int RPL_TRACEUSER = 205;
  static int RPL_TRACESERVER = 206;
  static int RPL_TRACESERVICE = 207;
  static int RPL_TRACENEWTYPE = 208;
  static int RPL_TRACECLASS = 209;
  static int RPL_TRACERECONNECT = 210;
  static int RPL_TRACELOG = 261;
  static int RPL_TRACEEND = 262;
  static int RPL_STATSLINKINFO = 211;
  static int RPL_STATSCOMMANDS = 212;
  static int RPL_ENDOFSTATS = 219;
  static int RPL_STATSUPTIME = 242;
  static int RPL_STATSOLINE = 243;
  static int RPL_UMODEIS = 221;
  static int RPL_SERVLIST = 234;
  static int RPL_SERVLISTEND = 235;
  static int RPL_LUSERCLIENT = 251;
  static int RPL_LUSEROP = 252;
  static int RPL_LUSERUNKNOWN = 253;
  static int RPL_LUSERCHANNELS = 254;
  static int RPL_LUSERME = 255;
  static int RPL_ADMINME = 256;
  static int RPL_ADMINLOC1 = 257;
  static int RPL_ADMINLOC2 = 258;
  static int RPL_ADMINEMAIL = 259;
  static int RPL_TRYAGAIN = 263;
}