part of IrcModule;

class STRINGS {
  static RegExp servername;
  static RegExp nickname;
  static RegExp host;
  static RegExp message;
  static RegExp prefix;
  static RegExp mode;
  static RegExp nospcrlfcl;
  static RegExp middle;
  static RegExp trailing;
  static String space = " ";
  static String crlf = new Utf8Decoder().convert([13,10]);
}


class CLIENT_COMMANDS {
  static const String PASS = "PASS";
  static const String NICK = "NICK";
  static const String USER = "USER";
  static const String OPER = "OPER";
  static const String USER_MODE = "MODE";
  static const String SERVICE = "SERVICE";
  static const String QUIT = "QUIT";
  static const String SQUIT = "SQUIT";
  static const String JOIN = "JOIN";
  static const String PART = "PART";
  static const String CHAN_MODE = "MODE";
  static const String TOPIC = "TOPIC";
  static const String NAMES = "NAMES";
  static const String LIST = "LIST";
  static const String INVITE = "INVITE";
  static const String KICK = "KICK";
  static const String PRIV_MSG = "SQUIT";
  static const String NOTICE = "NOTICE";
  static const String MOTD = "MOTD";
  static const String L_USERS = "LUSERS";
  static const String VERSION = "VERSION";
  static const String STATS = "STATS";
  static const String LINKS = "LINKS";
  static const String TIME = "TIME";
  static const String CONNECT = "CONNECT";
  static const String TRACE = "TRACE";
  static const String ADMIN = "ADMIN";
  static const String INFO = "INFO";
  static const String SERV_LIST = "SERVLIST";
  static const String SQUERY = "SQUERY";
  static const String WHO = "WHO";
  static const String WHO_IS = "WHOIS";
  static const String WHO_WAS = "WHOWAS";
  static const String KILL = "KILL";
  static const String PING = "PING";
  static const String PONG = "PONG";
  static const String ERROR = "ERROR";
  static const String AWAY = "AWAY";
  static const String REHASH = "REHASH";
  static const String DIE = "DIE";
  static const String RESTART = "RESTART";
  static const String SUMMON= "SUMMON";
  static const String USERS = "USERS";
  static const String WALL_OPS = "WALLOPS";
  static const String USER_HOST = "USERHOST";
  static const String IS_ON = "ISON";
  
}
class NUMERIC5_PARAM {
  static const String CMDS = "CMDS";
  static const String PREFIX = "PREFIX";
  static const String CHAN_TYPES = "CHANTYPES";
  static const String CHAN_MODES = "CHANMODES";
  static const String MODES = "MODES";
  static const String MAX_CHANNELS = "MAXCHANNELS";
  static const String CHAN_LIMIT = "CHANLIMIT";
  static const String NICK_LENGTH = "NICKLEN";
  static const String MAX_BANS = "MAXBANS";
  static const String MAX_LIST = "MAXLIST";
  static const String NETWORK = "NETWORK";
  static const String EXCEPTS = "EXCEPTS";
  static const String INVEX = "INVEX";
  static const String WALL_CHANNEL_OPS = "WALLCHOPS";
  static const String WALL_VOICES = "WALLVOICES";
  static const String CASE_MAPPING = "CASEMAPPING";
  static const String EXTENSIONS_LIST = "ELIST";
  static const String TOPIC_LENGTH = "TOPICLEN";
  static const String KICK_LENGTH = "KICKLEN";
  static const String CHANNEL_LENGTH = "CHANNELLEN";
  static const String CHANNEL_ID_LENGTH = "CHIDLEN";
  static const String ID_CHANNEL = "IDCHAN";
  static const String STANDARD = "STD";
  static const String SILENCE = "SILENCE";
  static const String RFC2812 = "RFC2812";
  static const String PENALTY = "PENALTY";
  static const String FNC = "FNC";
  static const String SAFELIST = "SAFELIST";
  static const String AWAY_LENGTH = "AWAYLEN";
  static const String NO_QUIT = "NOQUIT";
  static const String USER_IP = "USERIP";
  static const String CHANNEL_PRIVATE_MESSAGE = "CPRIVMESSAGE";
  static const String CHANNEL_NOTICE = "CNOTICE";
  static const String MAX_NICK_LENGTH = "MAXNICKLEN";
  static const String MAX_TARGETS = "MAXTARGETS";
  static const String KNOCK = "KNOCK";
  static const String VIRTUAL_CHANNELS = "VCHANS";
  static const String WATCH = "WATCH";
  static const String WHOX = "WHOX";
  static const String CALLER_ID = "CALLERID";
  static const String ACCEPT = "ACCEPT";
  static const String LANGUAGE = "LANGUAGE";
}

class NUMERIC_REPLIES {
  // Errors

  static const int ERR_NOSUCHNICK = 401;
  static const int ERR_NOSUCHSERVER = 402;
  static const int ERR_NOSUCHCHANNEL = 403;
  static const int ERR_CANNOTSENDTOCHAN = 404;
  static const int ERR_TOOMANYCHANNELS = 405;
  static const int ERR_WASNOSUCHNICK = 406;
  static const int ERR_TOOMANYTARGETS = 407;
  static const int ERR_NOSUCHSERVICE = 408;
  static const int ERR_NOORIGIN = 409;
  static const int ERR_NORECIPIENT = 411;
  static const int ERR_NOTEXTTOSEND = 412;
  static const int ERR_NOTOPLEVEL = 413;
  static const int ERR_WILDTOPLEVEL = 414;
  static const int ERR_BADMASK = 415;
  static const int ERR_UNKNOWNCOMMAND = 421;
  static const int ERR_NOMOTD = 422;
  static const int ERR_NOADMININFO = 423;
  static const int ERR_FILEERROR = 424;
  static const int ERR_NONICKNAMEGIVEN = 431;
  static const int ERR_ERRONEUSNICKNAME = 432;
  static const int ERR_NICKNAMEINUSE = 433;
  static const int ERR_NICKCOLLISION = 436;
  static const int ERR_UNAVAILRESOURCE = 437;
  static const int ERR_USERNOTINCHANNEL = 441;
  static const int ERR_NOTONCHANNEL = 442;
  static const int ERR_USERONCHANNEL = 443;
  static const int ERR_NOLOGIN = 444;
  static const int ERR_SUMMONDISABLED = 445;
  static const int ERR_USERSDISABLED = 446;
  static const int ERR_NOTREGISTERED = 451;
  static const int ERR_NEEDMOREPARAMS = 461;
  static const int ERR_ALREADYREGISTRED = 462;
  static const int ERR_NOPERMFORHOST = 463;
  static const int ERR_PASSWDMISMATCH = 464;
  static const int ERR_YOUREBANNEDCREEP = 465;
  static const int ERR_YOUWILLBEBANNED = 466;
  static const int ERR_KEYSET = 467;
  static const int ERR_CHANNELISFULL = 471;
  static const int ERR_UNKNOWNMODE = 472;
  static const int ERR_INVITEONLYCHAN = 473;
  static const int ERR_BANNEDFROMCHAN = 474;
  static const int ERR_BADCHANNELKEY = 475;
  static const int ERR_BADCHANMASK = 476;
  static const int ERR_NOCHANMODES = 477;
  static const int ERR_BANLISTFULL = 478;
  static const int ERR_NOPRIVILEGES = 481;
  static const int ERR_CHANOPRIVSNEEDED = 482;
  static const int ERR_CANTKILLSERVER = 483;
  static const int ERR_RESTRICTED = 484;
  static const int ERR_UNIQOPPRIVSNEEDED = 485;
  static const int ERR_NOOPERHOST = 491;
  static const int ERR_UMODEUNKNOWNFLAG = 501;
  static const int ERR_USERSDONTMATCH = 502;
  
  // Replies
  static const int RPL_WELCOME = 001;
  static const int RPL_YOUREHOST = 002;
  static const int RPL_CREATED = 003;
  static const int RPL_MYINFO = 004;
  static const int RPL_BOUNCE = 005;
  static const int RPL_USERHOST = 302;
  static const int RPL_ISON = 303;
  static const int RPL_AWAY = 301;
  static const int RPL_UNAWAY = 305;
  static const int RPL_NOWAWAY = 306;
  static const int RPL_WHOISUSER = 311;
  static const int RPL_WHOISSERVER = 312;
  static const int RPL_WHOISOPERATOR = 313;
  static const int RPL_WHOISIDLE = 317;
  static const int RPL_ENDOFWHOIS = 318;
  static const int RPL_WHOISCHANNELS = 319;
  static const int RPL_WHOWASUSER = 314;
  static const int RPL_ENDOFWHOWAS = 369;
  
  // @depreciated 
  static const int RPL_LISTSTART = 321;
  
  static const int RPL_LIST = 322;
  static const int RPL_LISTEND = 323;
  static const int RPL_UNIQOPIS = 325;
  static const int RPL_CHANNELMODEIS = 324;
  static const int RPL_INVITING = 341;
  static const int RPL_SUMMONING = 342;
  static const int RPL_INVITELIST = 346;
  static const int RPL_ENDOFINVITELIST = 347;
  static const int RPL_EXCEPTLIST = 348;
  static const int RPL_ENDOFEXCEPTLIST = 349;
  static const int RPL_VERSION = 351;
  static const int RPL_WHOREPLY = 352;
  static const int RPL_ENDOFWHO = 315;
  static const int RPL_NAMREPLY = 353;
  static const int RPL_ENDOFNAMES = 366;
  static const int RPL_LINKS = 364;
  static const int RPL_ENDOFLINKS = 365;
  static const int RPL_BANLIST = 367;
  static const int RPL_ENDOFBANLIST = 368;
  static const int RPL_INFO = 371;
  static const int RPL_ENDOFINFO = 374;
  static const int RPL_MOTDSTART = 375;
  static const int RPL_MOTD = 372;
  static const int RPL_ENDOFMOTD = 376;
  static const int RPL_YOUREOPER = 381;
  static const int RPL_REHASHING = 382;
  static const int RPL_YOURESERVICE = 383;
  static const int RPL_TIME = 391;
  static const int RPL_USERSSTART = 392;
  static const int RPL_USERS = 393;
  static const int RPL_ENDOFUSERS = 394;
  static const int RPL_NOUSERS = 395;
  static const int RPL_TRACELINK = 200;
  static const int RPL_TRACECONNECTING = 201;
  static const int RPL_TRACEHANDSHAKE = 202;
  static const int RPL_TRACEUNKNOWN = 203;
  static const int RPL_TRACEOPERATOR = 204;
  static const int RPL_TRACEUSER = 205;
  static const int RPL_TRACESERVER = 206;
  static const int RPL_TRACESERVICE = 207;
  static const int RPL_TRACENEWTYPE = 208;
  static const int RPL_TRACECLASS = 209;
  static const int RPL_TRACERECONNECT = 210;
  static const int RPL_TRACELOG = 261;
  static const int RPL_TRACEEND = 262;
  static const int RPL_STATSLINKINFO = 211;
  static const int RPL_STATSCOMMANDS = 212;
  static const int RPL_ENDOFSTATS = 219;
  static const int RPL_STATSUPTIME = 242;
  static const int RPL_STATSOLINE = 243;
  static const int RPL_UMODEIS = 221;
  static const int RPL_SERVLIST = 234;
  static const int RPL_SERVLISTEND = 235;
  static const int RPL_LUSERCLIENT = 251;
  static const int RPL_LUSEROP = 252;
  static const int RPL_LUSERUNKNOWN = 253;
  static const int RPL_LUSERCHANNELS = 254;
  static const int RPL_LUSERME = 255;
  static const int RPL_ADMINME = 256;
  static const int RPL_ADMINLOC1 = 257;
  static const int RPL_ADMINLOC2 = 258;
  static const int RPL_ADMINEMAIL = 259;
  static const int RPL_TRYAGAIN = 263;
}